---
name: Incident Report Template
about: Incident Report ticket
title: "INCIDENT (XX Jan 2021): Some short description about the incident"
labels: "incident"
assignees: ""

---

<!-- Do not leave any section empty. -->

# 1. Executive Summary
<!--
    Executive Summary should contain about up to 3 paragraphs to clarify what
    happened. Bear in mind that this is targeted for Business Users as well,
    meaning technical details should be kept minimal.

    This is a REQUIRED field.
-->

<!--EXAMPLE-->
Redacted
<!--EXAMPLE END-->

# 2. Business Impact
...
